# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField()),
                ('room_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_code', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('course_type', models.CharField(max_length=255)),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=255)),
                ('faculty_type', models.CharField(max_length=255)),
                ('faculty_contact', models.IntegerField()),
                ('sex', models.CharField(max_length=255)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thyme.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('semester', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thyme.Course')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thyme.Faculty')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thyme.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('batch', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thyme.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('slot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('slot_type', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thyme.Timeslot'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thyme.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thyme.Faculty'),
        ),
    ]
