# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thyme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='semester',
        ),
    ]
